# Generated by Django 5.1.7 on 2025-03-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(default='לא ידוע', max_length=50),
        ),
    ]
